### ISSUE TITLE
Needs package.json and publish to npm

### ISSUE THREAD

**Issue by coolaj86** [jonatkins/s2-geometry-javascript#6]
Once we have a license I'll create the `package.json` and publish (and add you as owner if you have an npm username)

**Comment by jonatkins** [comment]
To be honest, I've pretty much abandoned this project. It was written a few years for one job - part of the IITC project (the unofficial map for Ingress - Niantic's first game), and made a separate project as it was useful on it's own.

I've since moved on from IITC, and this has been sitting here for ages, with no interest from others. Feel free to take over future development, publishing, etc.

**Comment by coolaj86** [comment]
Would you like to transfer ownership?

You can go to the [transfer ownership](https://github.com/jonatkins/s2-geometry-javascript/settings) section at the bottom of the [settings page](https://github.com/jonatkins/s2-geometry-javascript/settings), click 'transfer' and choose to transfer `s2-geometry-javascript` to `Daplie`.

I'll create an AUTHORS file and give you proper attribution.

Thanks for creating this. It seems that INGRESS and Pokemon GO are the only popular projects that use s2 geometry, and with with the explosion of Pokemon GO it's definitely much needed now.

**Comment by coolaj86** [comment]
bump?

**Comment by coolaj86** [comment]
Published https://www.npmjs.com/package/s2-geometry
